name: dstore_middleware_dio
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  dstore:
    git:
      url: https://github.com/chandu0101/dstore
      path: packages/dstore
  dio: ^4.0.0
dev_dependencies:
  pedantic:
  
      

