openapi: "3.0.0"
info:
  version: 1.0.0
  title: Genric Dart backend
  license:
    name: MIT
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: Hello MEssage
      operationId: helloPing
      tags:
        - pets
      responses:
        '200':
          description: Hello world message
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/StringRef"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /siva:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StringRef"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    StringRef:
      type: string 
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string