targets:
  $default:
    builders:
      dstore_generator:
        options:
          compact_query_methods: true
      dstore_generator:ps:
        options:
          persistMode: ExplicitPersist     