name: dstore_example
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  dstore:
    path: ../dstore
  json_annotation: 4.0.0
  freezed_annotation:
  union: 0.0.4-nullsafety.1  

dev_dependencies:
  build_runner: ^1.10.13
  pedantic:
  grinder: 
  dstore_generator:
    path: ../dstore_generator
  json_serializable: 4.0.1
      

