builders:
  dstore_generator|gql:
    import: "package:dstore_generator/builder.dart"
    builder_factories: ["dstoreGqlGen"]
    build_extensions: {".dart": [".dstore.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before: ["dstore_generator|ps"]
  dstore_generator|ps:
    import: "package:dstore_generator/builder.dart"
    builder_factories: ["dstorePSGen"]
    build_extensions: {".dart": [".dstore.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before: ["dstore_generator"]
  dstore_generator:
    import: "package:dstore_generator/builder.dart"
    builder_factories: ["dstoreGen"]
    build_extensions: {".dart": [".dstore.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before: []  