builders:
  dstore_generator:
    import: "package:dstore_generator/builder.dart"
    builder_factories: ["dstoreGen"]
    build_extensions: {".dart": [".dstore.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before: ["dstore_generator|dstore_generator"]