name: dstore_generator
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  analyzer: ^0.41.2  # Pin the analyzer version to work around generatiuon failure
  build: ^1.6.1
  build_config: ^0.4.5 
  meta: 
  source_gen: ^0.9.10+1 
  ansicolor: ^1.1.1
  gql:
  dio: 
  dstore:
    path: ../dstore

dev_dependencies:
  pedantic: 
    
