name: dstore_generator
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  analyzer: ^1.1.0
  build: ^2.0.0
  build_config: ^0.4.6 
  meta: ^1.3.0 
  source_gen: ^1.0.0
  gql:
  crypto: 
  dio: 4.0.0-beta1
  collection:
  timing:
  yaml:    
  ansicolor: 2.0.0-nullsafety.0
  logging: 1.0.0
  tuple:
  open_api_schema:
    path: ../../../open_api_schema/
  path_to_regexp: 
  json_annotation: ^4.0.1
  dstore_annotation:
    path: ../dstore_annotation
  dstore_dgraph:
    path: ../dgraph
  dotenv:
      

dev_dependencies:
  pedantic: 1.10.0
  build_runner: ^1.12.2
  grinder: 0.9.0-nullsafety.0
  json_serializable: ^4.1.0
  test: 
  
    
