name: dstore_generator
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  analyzer:  # Pin the analyzer version to work around generatiuon failure
  build: 
  build_config: 
  meta: 
  source_gen: 
  dstore:
    path: ../dstore

dev_dependencies:
    
