name: dstore_generator
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  analyzer: ^1.1.0
  build: ^1.6.3
  build_config: ^0.4.6 
  meta: ^1.3.0 
  source_gen: ^0.9.10+3
  gql:
  dio: 4.0.0-beta1 
  dstore:
    path: ../dstore
  collection:
  ansicolor: 2.0.0-nullsafety.0
  logging: 1.0.0  

dev_dependencies:
  pedantic: 
    
