name: dstore_generator
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  analyzer: "0.39.14" # Pin the analyzer version to work around generatiuon failure
  build: ">=0.12.6 <2.0.0"
  build_config: ">=0.4.2 <1.0.0"
  meta: ^1.1.0
  source_gen: ^0.9.0
  dstore:
    path: ../dstore

dev_dependencies:
    
