name: dstore_generator
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  analyzer: ^1.7.0
  build: ^2.0.1
  meta: ^1.4.0 
  source_gen: ^1.0.0
  gql: ^0.13.0 
  crypto: 
  dio: ^4.0.0
  collection:
  timing:
  yaml:    
  ansicolor: 2.0.0-nullsafety.0
  tuple:
  open_api_schema:
    git:
      url: https://github.com/chandu0101/open_api_schema
  path_to_regexp: 
  dstore_annotation:
    git:
      url: https://github.com/chandu0101/dstore
      path: packages/dstore_annotation
  dstore_dgraph:
    git:
      url: https://github.com/chandu0101/dstore
      path: packages/dgraph
  dotenv:
      

dev_dependencies:
  pedantic: 1.10.0
  build_runner: ^2.0.4
  grinder: 
  json_serializable: ^4.1.0
  test: 
  
    
