name: dstore
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=2.13.0-0 <3.0.0"
dependencies:
  meta: ^1.4.0
  collection: ^1.15.0
  dstore_annotation:
    git:
      url: https://github.com/chandu0101/dstore
      path: packages/dstore_annotation
  

dev_dependencies:
  pedantic: 1.10.0
  test:
  time:   
  build_runner: 
  grinder: 0.9.0-nullsafety.0
  json_serializable: 
  async: 
  dstore_generator:
   git:
      url: https://github.com/chandu0101/dstore
      path: packages/dstore_generator
  fast_immutable_collections:  
